del c-convert.o 
del c-decl.o 
del c-parse-tab.o 
del c-typeck.o 
del caller-save.o 
del cccp.o 
del cexp.o 
del combine.o 
del cse.o 
del emit-rtl.o 
del explow.o 
del expmed.o 
del expr.o 
del final.o 
del flow.o 
del fold-const.o 
del gcc.o 
del global-alloc.o 
del insn-emit.o 
del insn-extract.o 
del insn-output.o 
del insn-peep.o 
del insn-recog.o 
del integrate.o 
del jump.o 
del lastfile.o 
del local-alloc.o 
del loop.o 
del main.o 
del obstack.o 
del optabs.o 
del print-tree.o 
del recog.o 
del regclass.o 
del reload.o 
del reload1.o 
del rtl.o 
del rtlanal.o 
del sdbout.o 
del stmt.o 
del stor-layout.o 
del stupid.o 
del toplev.o 
del trap.o 
del trap14.o 
del trapgcc.o 
del tree.o 
del varasm.o 
del version.o 
del x68k-extra.o 
del cc1.x
del cpp.x
del gccnew.x
del 1stcc1.x
del 2ndcc1.x
del 1stcpp.x
del 2ndcpp.x
del 1stgcc.x
del 2ndgcc.x
rm insn-*.*
rm s-*
rm h*.x
rm hgcc.o
ren botcc1.x gcc_cc1.x
ren botcpp.x gcc_cpp.x
ren botgcc.x gcc.x
